// Generated by CoffeeScript 1.7.1
(function($) {
  return $.extend({
    jHtml: {
      parse: function(json, callback) {
        var domString, traverse;
        domString = "";
        traverse = function(obj) {
          var attr, i, val, _ref, _results;
          i = 0;
          _results = [];
          while (i < obj.length) {
            domString += "<";
            domString += obj[i];
            domString += " ";
            _ref = obj[i + 1];
            for (attr in _ref) {
              val = _ref[attr];
              domString += attr;
              domString += "=";
              domString += "'";
              domString += val;
              domString += "' ";
            }
            domString += ">";
            if (obj[i + 2] instanceof Array) {
              traverse(obj[i + 2]);
            } else {
              domString += obj[i + 2];
            }
            domString += "</";
            domString += obj[i];
            domString += ">";
            _results.push(i += 3);
          }
          return _results;
        };
        traverse(json);
        if (callback) {
          callback(domString);
        }
        return domString;
      },
      validate: function(json) {},
      fetch: function(url, callback) {
        var that;
        that = this;
        return $.ajax({
          method: "get",
          url: url,
          contentType: "application/json",
          success: function(res) {
            return callback(that.parse(res));
          }
        });
      },
      template: (function(){
          'use strict';
          var SPACE_RE = /[\r\t\n]/g,
              QUOTE_RE = /'/g,
              ESC_QUOTE_RE = /\\'/g,
              proc = function(all, g1){
                  var s = g1.replace(ESC_QUOTE_RE, "'");
                  return s.charAt(0) === '=' ? ("'+" + s.slice(1) + "+'") : ("';" + s + "s+='");
              };

          function tmpl(str,varName){
              varName = varName || "data";

              return new Function(varName, "var s='" +
                  str.replace(SPACE_RE, " ").replace(QUOTE_RE, "\\'").replace(tmpl.procRe, proc) + "';return s;");
          }

          tmpl.procRe = /{{(.+?)}}/g;

          return tmpl;
      }())
    }
  });
})($);
